install:
    - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended 
    - sudo apt-get install chktex
 
script:
    - make
    - chktex -W # Print version information.
    #- chktex -q -n 6 *.tex chapters.*.tex 2>/dev/null | tee lint.out
    # If lint output is non-empty report an error.
    #- test ! -s lint.
deploy:
  provider: releases
  api-key: "4cc94e8957a9c831e452fc6c38fe5655134f48a9"
  file: "relazione.pdf"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
